runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

# static, use by backend... graphql frontend sits here
- url: /static
  static_dir: static
  http_headers:
    Access-Control-Allow-Origin: http://localhost:4200

# static angular files (dist content from build)
- url: /angular
  static_dir: angular

# new api route!
- url: /api/.*
  script: public-ink.app

# certificate validation
- url: /\.well-known/acme-challenge/.*
  script: public-ink.app

# serve index.html at all other urls
- url: /.*
  static_files: angular/index.html
  upload: angular/index.html

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^(.*/)?\soundfonts(.*/)?$